--- #YAML:1.0
name:                Net-CyanChat
version:             0.07
abstract:            Perl interface for connecting to Cyan Worlds' chat room.
license:             ~
author:
    - Noah Petherbridge
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
